"""empty message

Revision ID: 081deebca4c2
Revises: 2bcaaedc7330
Create Date: 2019-12-12 00:53:59.556062

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '081deebca4c2'
down_revision = '2bcaaedc7330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('body', sa.String(length=40), nullable=True))
    op.drop_column('message', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('content', mysql.VARCHAR(length=40), nullable=True))
    op.drop_column('message', 'body')
    # ### end Alembic commands ###
