"""removed test

Revision ID: 0841a8d8cf6a
Revises: b9856975e6cb
Create Date: 2019-12-10 18:51:39.477172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0841a8d8cf6a'
down_revision = 'b9856975e6cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('test', mysql.VARCHAR(length=120), nullable=True))
    # ### end Alembic commands ###
