"""updated content to body

Revision ID: 2ce5a55f8be1
Revises: 0841a8d8cf6a
Create Date: 2019-12-11 16:08:07.315964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ce5a55f8be1'
down_revision = '0841a8d8cf6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('body', sa.String(length=40), nullable=True))
    op.drop_column('message', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('content', mysql.VARCHAR(length=40), nullable=True))
    op.drop_column('message', 'body')
    # ### end Alembic commands ###
