"""empty message

Revision ID: 3c3f5b91ad45
Revises: cdd233f7d0ac
Create Date: 2019-12-15 19:10:37.943230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c3f5b91ad45'
down_revision = 'cdd233f7d0ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', sa.String(length=240), nullable=True))
    op.add_column('post', sa.Column('image', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_index('ix_user_hash_id', table_name='user')
    op.drop_column('user', 'hash_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hash_id', mysql.VARCHAR(length=256), nullable=True))
    op.create_index('ix_user_hash_id', 'user', ['hash_id'], unique=True)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'username')
    op.drop_column('post', 'image')
    op.drop_column('post', 'body')
    # ### end Alembic commands ###
