"""empty message

Revision ID: 51d831b18cd9
Revises: 
Create Date: 2019-12-17 12:31:15.730927

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51d831b18cd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('price', mysql.FLOAT(), nullable=True))
    # ### end Alembic commands ###
