"""Added backref to User for message

Revision ID: 6ffb951edac2
Revises: 2ce5a55f8be1
Create Date: 2019-12-11 20:17:52.412714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ffb951edac2'
down_revision = '2ce5a55f8be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('body', sa.String(length=40), nullable=True))
    op.drop_column('message', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('content', mysql.VARCHAR(length=40), nullable=True))
    op.drop_column('message', 'body')
    # ### end Alembic commands ###
