"""changed image from db.string to column

Revision ID: 77a45ba64f31
Revises: 6f67e1c8a344
Create Date: 2019-12-09 18:45:43.045134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a45ba64f31'
down_revision = '6f67e1c8a344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'image')
    # ### end Alembic commands ###
