"""Test

Revision ID: b9856975e6cb
Revises: 77a45ba64f31
Create Date: 2019-12-10 13:54:32.456671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9856975e6cb'
down_revision = '77a45ba64f31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('test', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'test')
    # ### end Alembic commands ###
