"""empty message

Revision ID: cdd233f7d0ac
Revises: 7e395564257e
Create Date: 2019-12-15 18:40:18.383810

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cdd233f7d0ac'
down_revision = '7e395564257e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'body')
    op.drop_column('post', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image', mysql.VARCHAR(length=256), nullable=True))
    op.add_column('post', sa.Column('body', mysql.VARCHAR(length=240), nullable=True))
    # ### end Alembic commands ###
