"""changed user_id to email in Post table

Revision ID: e381c278b15a
Revises: 6d089b1f162a
Create Date: 2019-12-12 01:35:38.282415

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e381c278b15a'
down_revision = '6d089b1f162a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('user_email', sa.Integer(), nullable=True))
    op.drop_constraint('post_ibfk_2', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['user_email'], ['email'])
    op.drop_column('post', 'user_id')
    op.drop_index('ix_user_hash_id', table_name='user')
    op.create_index(op.f('ix_user_hash_id'), 'user', ['hash_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_hash_id'), table_name='user')
    op.create_index('ix_user_hash_id', 'user', ['hash_id'], unique=False)
    op.add_column('post', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_ibfk_2', 'post', 'user', ['user_id'], ['id'])
    op.drop_column('post', 'user_email')
    # ### end Alembic commands ###
