"""import database

Revision ID: fdea49a9c129
Revises: 
Create Date: 2019-12-07 00:05:37.412958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fdea49a9c129'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', sa.String(length=240), nullable=True))
    op.drop_column('post', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('description', mysql.VARCHAR(length=240), nullable=True))
    op.drop_column('post', 'body')
    # ### end Alembic commands ###
